# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql
    networks:
        - default
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        - default
  www:
    build: .
    ports: 
        - "8001:80"
    volumes:
        - ./www:/var/www/html/
    links:
        - db
    networks:
      - default
volumes:
    persistent: {}